server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://<host>:<port>/<your_database>
    username: <your_username>
    password: <your_password>
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      indent_output: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# Cấu hình JWT
jwt:
  secret: <your_jwt_secret>
  expirationMs: 86400000 # 1 ngày

# Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
